---
- name: How to print with debug
  hosts: localhost
  gather_facts: yes

  vars:
    vendorip: '192.168.22.55'

  tasks:
   - name: Print a message variable
     debug:
       msg: "The vendor IP is {{ vendorip }}"
       # note that recall within the msg paramenter requires mustache-brackets
       
   - name: Print just the variable
     debug:
       var: vendorip
       verbosity: 3

